GET http://localhost:4000/api/product

###

POST http://localhost:4000/api/product
Content-Type: application/json

{
  "title": "Bolar hat",
  "description": "bolar",
  "price": 2000,
  "photo": "https://i.imgur.com/in5lkpa.jpeg",
  "categories": "array",
  "stock": 9
}

###

PUT http://localhost:4000/api/product/1234
Content-Type: application/json

{
  
}

###

DELETE http://localhost:4000/api/product/1234