GET http://localhost:4000/api/product

###
GET http://localhost:4000/api/product/categories

###

POST http://localhost:4000/api/product
Content-Type: application/json

{
  "title": "test",
  "description": "test",
  "price": 1299,
  "photo": "tophat.jpg",
  "categories": ["Fancy"],
  "stock": 9
}


###

PUT http://localhost:4000/api/product/6287834d1a573fec1e165629
Content-Type: application/json

{
  "description": "edited"
}

###

DELETE http://localhost:4000/api/product/6287834d1a573fec1e165629