GET http://localhost:4000/api/product

###
GET http://localhost:4000/api/product/categories

###

POST http://localhost:4000/api/product
Content-Type: application/json

{
  "title": "test hat",
  "description": "loremdeoloaron onfseoe knfsoen",
  "price": 295,
  "photoId": "62987188e7b4e60b692e0db9",
  "categories": ["other, test"],
  "stock": 12,
  "qty": 0
}


###

PUT http://localhost:4000/api/product/628df3f4d8ee2cc23700f343
Content-Type: application/json

{
  "photoId": "628dfb84cd220a4afdab7908"
}

###

DELETE http://localhost:4000/api/product/6287834d1a573fec1e165629