GET http://localhost:3000/api/user

###

POST http://localhost:3000/api/user
Content-Type: application/json

{
  "firstName": "David",
  "lastName": "David",
  "password": "123"
}

###

PUT http://localhost:3000/api/user/1234
Content-Type: application/json

{
  
}

###

DELETE http://localhost:3000/api/user/1234