GET http://localhost:4000/api/user

###

POST http://localhost:4000/api/user
Content-Type: application/json

{
  "firstName": "philip",
  "lastName": "string",
  "password": "string",
  "email": "string",
  "phone": "string"
}

###

POST http://localhost:4000/api/user/login
Content-Type: application/json


{
  "email": "hazem@hazemmmmmmm",
  "password": "123456"
}

###

PUT http://localhost:4000/api/user/1234
Content-Type: application/json

{
  
}

###

DELETE http://localhost:4000/api/user/62863b3b04876d76186d2a70