GET http://localhost:4000/api/media/62987216e7b4e60b692e0dc3


###

GET http://localhost:4000/api/media/files

###

POST http://localhost:4000/api/media
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="media"; filename="bowlerHat.jpg"
Content-Type: image/jpeg

< ./client\src\assets\CategoriesPictures\bowlerHat.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

PUT http://localhost:4000/api/media/6297010dd716830e2c4c52e1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

{
  "filename": "postnord-full.png"
}

###

DELETE http://localhost:4000/api/media/628dfaa3cd220a4afdab7904


