GET http://localhost:4000/api/delivery

###
GET http://localhost:4000/api/delivery/628f3cd691ffef25d261f3a3

###

POST http://localhost:4000/api/delivery
Content-Type: application/json

{
  "name": "test",
  "altText": "Leverans till box, 1-2 arbetsdagar",
  "shippingTime": 2,
  "price": 29,
  "logo": "deliveryLogo",
  "id": "instabox"
}


###

PUT http://localhost:4000/api/delivery/628f40d8e63229379b584aac
Content-Type: application/json

{
  "name": "testar",
  "altText": "Leverans till box, 1-2 arbetsdagar",
  "shippingTime": 2,
  "price": 29,
  "logo": "deliveryLogo",
  "id": "instabox"
}

###

DELETE http://localhost:4000/api/delivery/628f40d8e63229379b584aac