GET http://localhost:4000/api/delivery

###
GET http://localhost:4000/api/delivery/628ddf2c2304eb3857ad2799

###

POST http://localhost:4000/api/delivery
Content-Type: application/json

{
  "name": "test",
  "altText": "Leverans till box, 1-2 arbetsdagar",
  "shippingTime": 2,
  "price": 29,
  "logo": "deliveryLogo",
  "id": "instabox"
}


###

PUT http://localhost:4000/api/delivery/6287834d1a573fec1e165629
Content-Type: application/json

{
  
}

###

DELETE http://localhost:4000/api/delivery/628df6b4a75c039582ae0bd7